import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/header/header"
import Main from "@/components/main/main"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Movie Project API',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Main />
        {children}
      </body>
    </html>
  )
}
