import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/header"
import ThemeSwitcher from "@/components/theme-switcher"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NET MOVIE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center w-full`}>
        <Header />
        <ThemeSwitcher />
        {children}
      </body>
    </html>
  )
}